# Generated by Django 5.2.11 on 2026-03-14 06:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_movimientorecurrente_ingreso'),
        ('inventario', '0002_remove_insumo_descripcion_remove_insumo_unidad_and_more'),
        ('mantenimientos', '0005_fotomantenimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egreso',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Egreso', 'verbose_name_plural': 'Egresos'},
        ),
        migrations.AddField(
            model_name='egreso',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='egreso',
            name='concepto',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='mantenimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='egresos', to='mantenimientos.mantenimiento'),
        ),
    ]
