from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal

class Migration(migrations.Migration):
 dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL),("contratos","0005_valor_tecnico_mensual"),("finanzas","0006_cuentas_por_cobrar_y_pagos"),("trabajadores","0002_alter_trabajador_options")]
 operations=[
 migrations.CreateModel(name="ObligacionTrabajador",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("periodo_anio",models.PositiveIntegerField(db_index=True)),("periodo_mes",models.PositiveIntegerField(db_index=True)),("valor_acordado",models.DecimalField(decimal_places=2,max_digits=12,validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),("estado",models.CharField(choices=[("pendiente","Pendiente"),("parcial","Parcial"),("pagado","Pagado"),("anulado","Anulado")],db_index=True,default="pendiente",max_length=12)),("observaciones",models.TextField(blank=True,default="")),("creada_en",models.DateTimeField(auto_now_add=True)),("actualizada_en",models.DateTimeField(auto_now=True)),("contrato",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="obligaciones_trabajador",to="contratos.contrato")),("trabajador",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="obligaciones_pago",to="trabajadores.trabajador"))],options={"ordering":["-periodo_anio","-periodo_mes","trabajador__user__username","id"],"verbose_name":"Obligación de pago a trabajador","verbose_name_plural":"Obligaciones de pago a trabajadores"}),
 migrations.CreateModel(name="PagoTrabajador",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("monto",models.DecimalField(decimal_places=2,max_digits=12,validators=[django.core.validators.MinValueValidator(Decimal("0.01"))])),("fecha",models.DateField(db_index=True)),("metodo_pago",models.CharField(choices=[("efectivo","Efectivo"),("transferencia","Transferencia"),("tarjeta","Tarjeta"),("deposito","Depósito"),("cheque","Cheque"),("otro","Otro")],default="transferencia",max_length=20)),("referencia",models.CharField(blank=True,default="",max_length=120)),("comprobante",models.FileField(blank=True,null=True,upload_to="finanzas/pagos_trabajadores/%Y/%m/")),("observaciones",models.TextField(blank=True,default="")),("activo",models.BooleanField(db_index=True,default=True)),("creado_en",models.DateTimeField(auto_now_add=True)),("actualizado_en",models.DateTimeField(auto_now=True)),("creado_por",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="pagos_trabajador_creados",to=settings.AUTH_USER_MODEL)),("egreso",models.OneToOneField(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="pago_trabajador",to="finanzas.egreso")),("obligacion",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="pagos",to="finanzas.obligaciontrabajador"))],options={"ordering":["-fecha","-id"],"verbose_name":"Pago a trabajador","verbose_name_plural":"Pagos a trabajadores"}),
 migrations.AddConstraint(model_name="obligaciontrabajador",constraint=models.UniqueConstraint(fields=("contrato","periodo_anio","periodo_mes"),name="unique_obligacion_trabajador_periodo"))]
