# Generated by Django 5.2.11 on 2026-02-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='unidad',
        ),
        migrations.AddField(
            model_name='insumo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
