# Generated by Django 5.2.11 on 2026-08-08 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_unidades_kg_litros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradastock',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Entrada de stock', 'verbose_name_plural': 'Entradas de stock'},
        ),
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'ordering': ['-creado_en', '-id'], 'verbose_name': 'Movimiento de inventario', 'verbose_name_plural': 'Movimientos de inventario'},
        ),
        migrations.AlterModelOptions(
            name='ventainsumo',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Venta de insumo', 'verbose_name_plural': 'Ventas de insumos'},
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.insumo'),
        ),
        migrations.AlterField(
            model_name='ventainsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='inventario.insumo'),
        ),
    ]
