# Generated by Django 5.2.11 on 2026-02-09 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimientos', '0002_alter_mantenimiento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('realizado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='mantenimientos.mantenimiento')),
            ],
            options={
                'verbose_name': 'Ítem de Checklist',
                'verbose_name_plural': 'Checklist de Mantenimiento',
            },
        ),
    ]
