# Generated by Django 5.2.11 on 2026-02-09 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_checklist', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Plantilla de Checklist',
                'verbose_name_plural': 'Plantillas de Checklist',
            },
        ),
    ]
