from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[('asistente_tecnico','0002_centro_conocimiento'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='ContenidoAcademia',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),
            ('tipo',models.CharField(choices=[('biblioteca','Biblioteca Técnica'),('procedimiento','Procedimiento'),('equipo','Equipo')],db_index=True,max_length=20)),
            ('codigo',models.CharField(max_length=40,unique=True)),('titulo',models.CharField(max_length=180)),('slug',models.SlugField(max_length=210,unique=True)),('resumen',models.CharField(blank=True,default='',max_length=320)),('imagen_principal',models.ImageField(blank=True,null=True,upload_to='academia/principales/')),
            ('nivel',models.CharField(choices=[('basico','Básico'),('intermedio','Intermedio'),('avanzado','Avanzado')],db_index=True,default='basico',max_length=20)),('tiempo_lectura_min',models.PositiveSmallIntegerField(default=5)),('estado',models.CharField(choices=[('borrador','Borrador'),('aprobado','Aprobado'),('archivado','Archivado')],db_index=True,default='borrador',max_length=20)),('version',models.CharField(default='1.0',max_length=20)),
            ('introduccion',models.TextField(blank=True,default='')),('contenido',models.TextField(blank=True,default='')),('procedimiento',models.TextField(blank=True,default='')),('herramientas_materiales',models.TextField(blank=True,default='')),('funcionamiento',models.TextField(blank=True,default='')),('componentes',models.TextField(blank=True,default='')),('mantenimiento',models.TextField(blank=True,default='')),('fallas_frecuentes',models.TextField(blank=True,default='')),('buenas_practicas',models.TextField(blank=True,default='')),('errores_comunes',models.TextField(blank=True,default='')),('recomendaciones_jvaqua',models.TextField(blank=True,default='')),('referencias_tecnicas',models.TextField(blank=True,default='')),('etiquetas',models.CharField(blank=True,default='',max_length=500)),('orden',models.PositiveSmallIntegerField(default=0)),('aprobado_en',models.DateTimeField(blank=True,null=True)),('creado_en',models.DateTimeField(auto_now_add=True)),('actualizado_en',models.DateTimeField(auto_now=True)),
            ('aprobado_por',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='contenidos_academia_aprobados',to=settings.AUTH_USER_MODEL)),('creado_por',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='contenidos_academia_creados',to=settings.AUTH_USER_MODEL)),('relacionados',models.ManyToManyField(blank=True,to='asistente_tecnico.contenidoacademia')),
        ],options={'verbose_name':'Contenido de Academia','verbose_name_plural':'Contenidos de Academia','ordering':['tipo','orden','titulo']}),
        migrations.CreateModel(name='ExperienciaConocimiento',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('titulo',models.CharField(max_length=180)),('problema',models.TextField()),('analisis',models.TextField(blank=True,default='')),('solucion',models.TextField(blank=True,default='')),('resultado',models.TextField(blank=True,default='')),('aprendizaje',models.TextField(blank=True,default='')),('estado',models.CharField(choices=[('borrador','Borrador'),('revision','En revisión'),('aprobada','Aprobada'),('descartada','Descartada')],db_index=True,default='borrador',max_length=20)),('destino_sugerido',models.CharField(blank=True,choices=[('','Sin convertir'),('biblioteca','Biblioteca Técnica'),('procedimiento','Procedimiento'),('equipo','Equipo')],default='',max_length=20)),('creado_en',models.DateTimeField(auto_now_add=True)),('actualizado_en',models.DateTimeField(auto_now=True)),
            ('convertido_en',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='experiencias_origen',to='asistente_tecnico.contenidoacademia')),('creado_por',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='experiencias_conocimiento_creadas',to=settings.AUTH_USER_MODEL)),('revisado_por',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='experiencias_conocimiento_revisadas',to=settings.AUTH_USER_MODEL)),
        ],options={'verbose_name':'Experiencia de conocimiento','verbose_name_plural':'Experiencias de conocimiento','ordering':['estado','-actualizado_en']}),
        migrations.CreateModel(name='ImagenContenidoAcademia',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('imagen',models.ImageField(upload_to='academia/galeria/')),('titulo',models.CharField(blank=True,default='',max_length=140)),('descripcion',models.CharField(blank=True,default='',max_length=280)),('orden',models.PositiveSmallIntegerField(default=0)),('creado_en',models.DateTimeField(auto_now_add=True)),('contenido',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='galeria',to='asistente_tecnico.contenidoacademia')),
        ],options={'verbose_name':'Imagen de Academia','verbose_name_plural':'Imágenes de Academia','ordering':['orden','id']}),
        migrations.CreateModel(name='VersionContenidoAcademia',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('version',models.CharField(max_length=20)),('snapshot',models.JSONField(default=dict)),('motivo',models.CharField(blank=True,default='',max_length=280)),('creado_en',models.DateTimeField(auto_now_add=True)),('contenido',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='versiones',to='asistente_tecnico.contenidoacademia')),('creado_por',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='versiones_academia_creadas',to=settings.AUTH_USER_MODEL)),
        ],options={'verbose_name':'Versión de contenido','verbose_name_plural':'Versiones de contenido','ordering':['-creado_en','-id']}),
        migrations.AddIndex(model_name='contenidoacademia',index=models.Index(fields=['tipo','estado'],name='ati_cms_tipo_estado_idx')),
        migrations.AddIndex(model_name='contenidoacademia',index=models.Index(fields=['estado','actualizado_en'],name='ati_cms_estado_act_idx')),
    ]
