from django.db import migrations


def seed_biblioteca(apps, schema_editor):
    Contenido = apps.get_model('asistente_tecnico', 'ContenidoAcademia')

    items = [
        {
            'codigo': 'BT-Q-001',
            'titulo': 'Cloro granulado',
            'slug': 'cloro-granulado',
            'resumen': 'Desinfectante y oxidante de acción rápida. En JVAQUA se utiliza en mantenimiento cuando hace falta elevar el cloro con rapidez y en tratamientos de choque.',
            'nivel': 'basico', 'tiempo_lectura_min': 9, 'orden': 10,
            'introduccion': '''El cloro granulado es uno de los productos principales para desinfectar el agua de una piscina. Según la formulación comercial puede tratarse de hipoclorito de calcio u otro cloro granular; por eso siempre debe revisarse la etiqueta del producto antes de dosificar.\n\nLO QUE DEBES RECORDAR\n• Primero mide pH y cloro.\n• La dosis no debe copiarse entre marcas si cambia el porcentaje de cloro disponible.\n• Nunca mezcles cloro seco con ácidos, otros cloros ni productos de piscina.\n• En JVAQUA el objetivo rutinario de cloro libre es 1–3 ppm, con referencia operativa cercana a 1,5 ppm.''',
            'contenido': '''¿PARA QUÉ SIRVE?\nEl cloro libre activo ayuda a inactivar microorganismos y a oxidar contaminantes que ingresan al agua. El hipoclorito de calcio es un oxidante fuerte y un desinfectante ampliamente usado en piscinas.\n\n¿CUÁNDO LO UTILIZA JVAQUA?\n• Mantenimiento normal cuando el nivel de cloro necesita subir con rapidez.\n• Agua ligeramente turbia cuando el técnico determina que hace falta un refuerzo de cloro.\n• Tratamientos de choque y recuperación, dentro del protocolo indicado por el Asistente Técnico.\n\n¿CUÁNDO NO DEBE APLICARSE A CIEGAS?\n• Sin medir previamente pH y cloro.\n• Si no se conoce la concentración del producto.\n• Junto con ácido, tricloro, dicloro u otros productos dentro del mismo recipiente.\n• Cuando el producto o la etiqueta del fabricante indiquen incompatibilidad con la superficie o el método de aplicación.''',
            'procedimiento': '''MANTENIMIENTO NORMAL JVAQUA\n1. Inspecciona el estado del agua.\n2. Mide pH y cloro.\n3. Corrige primero el pH cuando corresponda.\n4. Como referencia operativa interna, la calculadora JVAQUA utiliza 7 g/m³ para mantenimiento normal con cloro granulado; el técnico debe considerar la lectura real, el tipo de piscina, el uso y la concentración del producto.\n5. Aplica con la circulación funcionando y según la etiqueta del producto.\n6. Espera aproximadamente 10 minutos de circulación antes de volver a medir cuando estés ajustando parámetros.\n7. Comprueba que el cloro quede dentro del rango operativo.\n\nTRATAMIENTO DE CHOQUE JVAQUA\nEl objetivo operativo es elevar el cloro aproximadamente a 3–4 ppm. La cantidad concreta debe calcularse con el Asistente Técnico porque depende del volumen, lectura inicial y concentración del cloro utilizado.''',
            'funcionamiento': '''Los hipocloritos liberan especies de cloro desinfectante al disolverse en agua. La eficacia del cloro depende fuertemente del pH: por eso JVAQUA mide pH antes de decidir la dosificación. El cloro granular no estabilizado no aporta ácido cianúrico; esto lo diferencia de productos estabilizados como tricloro o dicloro.''',
            'buenas_practicas': '''• Utiliza utensilios limpios y completamente secos para medir producto seco.\n• Mantén el envase cerrado, fresco, seco y ventilado.\n• Usa protección ocular y guantes adecuados al producto.\n• Sigue siempre la etiqueta y FDS de la marca que estés utilizando.\n• Registra en el mantenimiento la cantidad realmente utilizada.\n• En piscinas de alto uso, decide la dosis según lectura y carga de bañistas, no únicamente por volumen.''',
            'errores_comunes': '''• Mezclar cloro con ácido: puede liberar gas cloro tóxico.\n• Mezclar distintos productos de cloro en un recipiente: puede provocar reacción violenta, incendio o gases tóxicos.\n• Echar una dosis fija sin medir el agua.\n• Asumir que todos los cloros granulados tienen la misma concentración.\n• Aplicar producto concentrado directamente sobre una superficie sensible cuando la etiqueta exige otro método.\n• Guardar producto húmedo o contaminarlo con residuos de otros químicos.''',
            'recomendaciones_jvaqua': '''REFERENCIA RÁPIDA JVAQUA\n• pH operativo: 7,2–7,6.\n• Cloro libre operativo: 1–3 ppm; referencia ideal habitual: ~1,5 ppm.\n• Mantenimiento normal con granulado: referencia interna 7 g/m³, siempre ajustada a lectura y producto.\n• Choque: llevar aproximadamente a 3–4 ppm mediante la calculadora.\n\nEn piscinas de urbanizaciones, hoteles o alto uso, la demanda puede ser mucho mayor. El técnico debe medir con mayor frecuencia y no extrapolar la dosis de una piscina residencial.''',
            'referencias_tecnicas': '''Fuentes de contraste técnico para revisión JVAQUA:\n• CDC Healthy Swimming — operación y tratamiento de piscinas: pH 7,0–7,8 y control de cloro libre.\n• EPA — Calcium Hypochlorite Supply Chain Profile: el hipoclorito de calcio es un oxidante fuerte y desinfectante de piscinas.\n• EPA Pesticide Product Labels para hipoclorito de calcio: seguir la etiqueta, no mezclar con otros químicos de piscina y respetar los límites de reingreso indicados por el producto.\n• PHTA — Calcium Hypochlorite fact sheet.\n\nNota: las dosis JVAQUA indicadas aquí son estándares internos sujetos a revisión según la concentración real del producto utilizado.''',
            'etiquetas': 'cloro, cloro granulado, hipoclorito de calcio, desinfección, choque, mantenimiento, oxidación, agua, químicos',
        },
        {
            'codigo': 'BT-Q-002', 'titulo': 'Tricloro en pastillas', 'slug': 'tricloro-en-pastillas',
            'resumen': 'Cloro estabilizado de disolución lenta utilizado por JVAQUA principalmente para mantener residual de cloro en piscinas en buenas condiciones.',
            'nivel': 'basico', 'tiempo_lectura_min': 8, 'orden': 20,
            'introduccion': '''El tricloro (tricloro-s-triazinetriona) es un desinfectante clorado estabilizado y de disolución lenta. Aporta cloro y, al mismo tiempo, incrementa el ácido cianúrico del agua. Es un producto ácido, por lo que con uso repetido puede contribuir a reducir el pH.\n\nLO QUE DEBES RECORDAR\n• Es ideal para mantenimiento sostenido cuando el agua está transparente.\n• No sustituye una medición de pH y cloro.\n• Su uso continuo aumenta el estabilizante (CYA).\n• Nunca debe mezclarse físicamente con hipoclorito de calcio u otros químicos.''',
            'contenido': '''En JVAQUA el tricloro es preferido cuando la piscina está transparente y se busca mantener un residual de desinfectante de forma sostenida. Al ser estabilizado, resiste mejor la degradación solar que un cloro no estabilizado, pero esa ventaja exige vigilar la acumulación de ácido cianúrico.\n\nIMPORTANTE\nEl efecto acidificante del tricloro se debe a la química propia del producto; no debe enseñarse que el tricloro contiene sulfato de aluminio como explicación general. Esta ficha corrige ese concepto para mantener el Manual Técnico alineado con la composición real del producto.''',
            'procedimiento': '''1. Mide pH y cloro.\n2. Si el agua está transparente y el cloro necesita mantenimiento sostenido, utiliza la pastilla según el sistema de dosificación disponible y la etiqueta.\n3. JVAQUA utiliza habitualmente pastillas de 200 g como unidad de referencia; la cantidad y frecuencia dependen del volumen, uso y lectura real.\n4. Evita colocar la pastilla en contacto directo prolongado con superficies sensibles.\n5. Revisa periódicamente el ácido cianúrico en piscinas con uso continuo de cloro estabilizado, aunque este parámetro no forme parte del checklist rutinario del trabajador.''',
            'funcionamiento': '''El tricloro libera ácido hipocloroso al entrar en contacto con el agua y aporta ácido cianúrico como estabilizante. Tiene un contenido alto de cloro disponible y carácter ácido. Su disolución lenta permite mantener desinfección entre visitas, pero no es la herramienta principal para corregir rápidamente un déficit severo de cloro.''',
            'buenas_practicas': '''• Mantén las tabletas secas y en su envase original.\n• Usa un dosificador adecuado cuando sea posible.\n• Vigila pH y acumulación de CYA en usos prolongados.\n• Mantén separados físicamente tricloro e hipocloritos.\n• Sigue la etiqueta del producto para la dosis y método de aplicación.''',
            'errores_comunes': '''• Mezclar tricloro con hipoclorito de calcio: riesgo grave de reacción.\n• Pensar que más pastillas siempre significa mejor desinfección.\n• Ignorar la acumulación de estabilizante.\n• Usar pastillas como sustituto de un tratamiento de choque cuando hace falta elevar rápidamente el cloro.\n• Depositar tabletas directamente sobre revestimientos sensibles.''',
            'recomendaciones_jvaqua': '''JVAQUA prioriza tricloro en piscinas transparentes y estables. Si el agua está ligeramente turbia o la demanda de cloro es alta, el técnico debe medir y decidir si corresponde reforzar con cloro granulado según el Asistente Técnico.''',
            'referencias_tecnicas': '''• EPA Reregistration Eligibility Document para cloroisocianuratos: el tricloro puede aportar ~90% de cloro disponible y libera ácido hipocloroso al contacto con agua.\n• CDC Healthy Swimming: cuando se utiliza ácido cianúrico o cloros estabilizados, debe considerarse su efecto sobre el manejo del residual de cloro.\n• EPA etiquetas de productos de tricloro: producto estabilizado, seguir estrictamente las instrucciones del fabricante.''',
            'etiquetas': 'tricloro, pastillas, cloro estabilizado, ácido cianúrico, cya, mantenimiento, desinfección',
        },
        {
            'codigo': 'BT-Q-003', 'titulo': 'Sulfato de aluminio', 'slug': 'sulfato-de-aluminio',
            'resumen': 'Floculante principal del protocolo JVAQUA para recuperar agua muy turbia o verde mediante sedimentación controlada.',
            'nivel': 'intermedio', 'tiempo_lectura_min': 10, 'orden': 30,
            'introduccion': '''El sulfato de aluminio es un coagulante/floculante. Ayuda a agrupar partículas finas suspendidas para formar flóculos que puedan sedimentar y luego retirarse por aspiración. Su adición consume alcalinidad y normalmente reduce el pH, por lo que el pH inicial es determinante.\n\nLO QUE DEBES RECORDAR\n• En JVAQUA es obligatorio en el proceso de floculación de agua muy turbia o verde.\n• Si el pH está alto, normalmente NO se añade reductor antes del sulfato.\n• Si el pH está bajo, se eleva antes para compensar la caída esperada.\n• La floculación se recomienda por 24 h; rango operativo 12–24 h.''',
            'contenido': '''El sulfato de aluminio no sustituye al cloro. Cumple otra función: retirar turbidez y material suspendido mediante coagulación/floculación. El tratamiento JVAQUA combina control de pH, shock de cloro cuando corresponde y sulfato de aluminio, seguido de reposo y aspirado del sedimento.\n\nLa efectividad depende de la química del agua. Un pH inadecuado puede reducir el rendimiento del proceso y provocar una corrección deficiente.''',
            'procedimiento': '''PROTOCOLO JVAQUA DE FLOCULACIÓN\n1. Determina el volumen de la piscina.\n2. Mide pH y cloro.\n3. Si el pH está alto: no utilices reductor de pH de forma automática; el sulfato tenderá a reducirlo.\n4. Si el pH está bajo: JVAQUA lo eleva aproximadamente hacia 7,8 antes de aplicar el sulfato, utilizando el corrector definido por el Asistente.\n5. Lleva el cloro al rango de choque indicado por el Asistente (aprox. 3–4 ppm).\n6. Aplica sulfato de aluminio. Referencia interna: 1 kg por aproximadamente 25 m³, tolerando ±5 m³; al superar claramente ese rango, la calculadora escala al siguiente nivel de dosis (ej.: 32 m³ → referencia JVAQUA 2 kg).\n7. Distribuye según el procedimiento operativo y deja reposar.\n8. Recomendación JVAQUA: 24 horas de sedimentación; mínimo operativo aproximado 12 h cuando la situación lo exige.\n9. Aspira el sedimento evitando devolverlo al filtro cuando el sistema permita aspirado a desagüe.\n10. Realiza el retrolavado/enjuague correspondiente y vuelve a medir pH y cloro.''',
            'funcionamiento': '''Al disolverse, las sales de aluminio forman especies que neutralizan cargas y favorecen la unión de partículas coloidales. El proceso puede consumir alcalinidad y reducir el pH. Por eso el control previo y posterior del pH es una parte central del método JVAQUA.''',
            'buenas_practicas': '''• Calcula el volumen antes de aplicar.\n• Mide pH y cloro antes y después.\n• Asegura un periodo real de reposo.\n• Aspira lentamente el sedimento para no volver a suspenderlo.\n• Revisa nivel de agua después de aspirar a desagüe.\n• Registra la dosis y el resultado para alimentar el aprendizaje del Asistente Técnico.''',
            'errores_comunes': '''• Aplicar sulfato sin medir pH.\n• Añadir reductor simplemente porque el pH está alto, sin considerar que el sulfato ya lo reducirá.\n• Confundir floculación con desinfección.\n• Encender circulación intensa durante el periodo en que debe sedimentar el flóculo.\n• Aspirar demasiado rápido y volver a levantar el sedimento.\n• Dar por terminado el proceso sin volver a medir parámetros.''',
            'recomendaciones_jvaqua': '''REFERENCIA RÁPIDA JVAQUA\n• Sulfato: ~1 kg / 25 m³ (±5 m³ como rango operativo interno).\n• Reposo: 24 h recomendado; 12–24 h según operación.\n• Shock de cloro: ~3–4 ppm.\n• Si pH está bajo: elevar previamente aproximadamente hacia 7,8.\n• Si pH está alto: evitar reductor automático y dejar que el sulfato contribuya a bajar pH.''',
            'referencias_tecnicas': '''• EPA Water Quality Criteria: la adición de sulfato de aluminio consume capacidad alcalina durante la coagulación.\n• Literatura técnica EPA sobre coagulación: el sulfato de aluminio es un coagulante utilizado para remover material suspendido/coloidal.\n• El protocolo de dosis y tiempos de esta ficha corresponde al método operativo JVAQUA y deberá validarse con la formulación comercial usada por la empresa.''',
            'etiquetas': 'sulfato de aluminio, floculación, floculante, agua turbia, agua verde, coagulación, choque',
        },
        {
            'codigo': 'BT-Q-004', 'titulo': 'Metasilicato / elevador de pH', 'slug': 'metasilicato-elevador-ph',
            'resumen': 'Producto alcalino utilizado por JVAQUA para elevar el pH cuando está bajo, aplicándolo de forma gradual, disuelta y con nueva medición.',
            'nivel': 'intermedio', 'tiempo_lectura_min': 8, 'orden': 40,
            'introduccion': '''JVAQUA utiliza metasilicato granulado y, en determinados tratamientos, material alcalino en polvo tipo cal P24 para elevar el pH. El metasilicato de sodio es fuertemente alcalino y debe manipularse con cuidado.\n\nLO QUE DEBES RECORDAR\n• Nunca corrijas pH sin medir.\n• JVAQUA aplica de forma gradual y vuelve a medir.\n• El producto se trabaja disuelto, no como una descarga concentrada sobre una superficie.\n• En floculación, si el pH está bajo, el objetivo previo puede ser mayor que el rango normal porque el sulfato volverá a bajarlo.''',
            'contenido': '''El pH bajo puede favorecer corrosión, agresividad del agua e incomodidad. El elevador de pH se utiliza para recuperar el rango de operación. Debido a que diferentes formulaciones tienen distinta alcalinidad, la dosis final debe confirmarse siempre con mediciones, no solo con una receta fija.''',
            'procedimiento': '''MANTENIMIENTO NORMAL JVAQUA\n1. Mide pH.\n2. Si está por debajo del rango, prepara una dosis pequeña disuelta.\n3. Referencia interna para metasilicato granulado: aproximadamente un puñado por cada 10 m³ como primer ajuste.\n4. Distribuye con filtración/circulación.\n5. Espera aproximadamente 10 minutos.\n6. Vuelve a medir.\n7. Repite únicamente si todavía hace falta.\n\nFLOCULACIÓN CON pH BAJO\nAntes del sulfato, JVAQUA puede elevar el pH aproximadamente hacia 7,8. Para producto alcalino en polvo tipo P24, la referencia interna indicada es 250–350 g por 25 m³, dependiendo de qué tan bajo esté el pH. Después se aplica el sulfato, que tenderá a reducir nuevamente el pH.''',
            'funcionamiento': '''El metasilicato de sodio es una sustancia alcalina utilizada industrialmente para elevar alcalinidad/pH. Su manipulación requiere protección porque soluciones concentradas pueden ser corrosivas para ojos y piel.''',
            'buenas_practicas': '''• Ajusta en pequeñas etapas.\n• Disuelve antes de distribuir, siguiendo el método interno y la etiqueta.\n• Mantén la circulación durante el ajuste.\n• Espera y vuelve a medir antes de repetir.\n• Utiliza guantes y protección ocular.\n• Diferencia claramente metasilicato granulado del producto alcalino en polvo usado por JVAQUA, ya que no deben asumirse concentraciones equivalentes.''',
            'errores_comunes': '''• Aplicar varias dosis seguidas sin esperar ni medir.\n• Echar producto concentrado directamente sobre el acabado.\n• Confundir “un puñado” con una dosis exacta universal: es una referencia práctica inicial, no un sustituto del test.\n• Usar la misma cantidad para formulaciones diferentes.\n• Manipular polvo alcalino sin protección ocular.''',
            'recomendaciones_jvaqua': '''REFERENCIA RÁPIDA JVAQUA\n• Rango normal de pH: 7,2–7,6.\n• Metasilicato granulado: primer ajuste aproximado de 1 puñado/10 m³, disuelto.\n• Retest: ~10 minutos.\n• Floculación con pH bajo: elevar aproximadamente hacia 7,8 antes del sulfato.\n• P24/polvo alcalino: referencia interna 250–350 g/25 m³ según lectura.''',
            'referencias_tecnicas': '''• OxyChem: sodium metasilicates are produced as highly alkaline granular products; consultar siempre SDS/especificación del producto específico.\n• CDC/PHTA: el pH de piscina debe mantenerse dentro de un rango controlado para confort, eficacia del desinfectante y protección de equipos.\n• Las dosis incluidas son procedimientos internos JVAQUA pendientes de validación final con la composición exacta del producto comercial usado.''',
            'etiquetas': 'metasilicato, ph bajo, subir ph, elevador ph, cal p24, alcalino, ajuste ph',
        },
        {
            'codigo': 'BT-Q-005', 'titulo': 'Alguicida', 'slug': 'alguicida',
            'resumen': 'Producto auxiliar para prevención y control de algas. JVAQUA lo utiliza como complemento, nunca como sustituto de la desinfección y el balance del agua.',
            'nivel': 'basico', 'tiempo_lectura_min': 7, 'orden': 50,
            'introduccion': '''El alguicida es un producto auxiliar para prevenir o controlar el desarrollo de algas. Existen formulaciones muy distintas (por ejemplo, compuestos de amonio cuaternario, polímeros o productos con metales), por lo que la etiqueta del producto concreto es obligatoria.\n\nLO QUE DEBES RECORDAR\n• Alguicida no significa “reemplazo del cloro”.\n• Identifica la formulación antes de mezclar o dosificar.\n• JVAQUA usa una referencia diferente para mantenimiento y para choque.\n• Evita sobredosificar porque algunas formulaciones pueden producir espuma o manchas.''',
            'contenido': '''En una piscina bien mantenida, el control principal depende de desinfección, circulación, filtración y balance químico. El alguicida funciona como apoyo preventivo o correctivo. La compatibilidad depende de la química del producto: algunos alguicidas cuaternarios pierden eficacia con ciertos detergentes y no deben mezclarse concentrados con oxidantes.''',
            'procedimiento': '''MANTENIMIENTO NORMAL JVAQUA\nReferencia interna: 2 g/m³, siempre considerando la formulación y etiqueta del producto.\n\nTRATAMIENTO DE CHOQUE / AGUA VERDE\nReferencia interna: 50 g por 25 m³ como complemento del protocolo de choque.\n\nPROCEDIMIENTO\n1. Mide pH y cloro.\n2. Determina si el alguicida corresponde al estado del agua.\n3. Confirma la formulación del producto y las instrucciones del fabricante.\n4. Dosifica de acuerdo con el volumen y el protocolo JVAQUA.\n5. Distribuye según la etiqueta, evitando mezclas concentradas con otros químicos.\n6. Registra la cantidad utilizada.''',
            'funcionamiento': '''Los mecanismos varían según el ingrediente activo. Los alguicidas de amonio cuaternario interactúan con membranas celulares; otras formulaciones emplean polímeros o iones metálicos. Esa diversidad es la razón por la que no debe enseñarse una compatibilidad universal para todos los alguicidas.''',
            'buenas_practicas': '''• Lee la etiqueta de la formulación específica.\n• Úsalo como complemento, no como sustituto del cloro.\n• Mantén una dosificación consistente y registrada.\n• Vigila aparición de espuma o manchas después de cambiar de producto.\n• Separa físicamente los concentrados y no hagas mezclas en recipientes.''',
            'errores_comunes': '''• Sobredosificar “por seguridad”.\n• Mezclar concentrado con cloro u otros oxidantes.\n• Usar la misma dosis para cualquier marca/formulación.\n• Intentar recuperar una piscina verde únicamente con alguicida.\n• Ignorar que productos con metales pueden aumentar riesgo de manchas si se usan incorrectamente.''',
            'recomendaciones_jvaqua': '''REFERENCIA RÁPIDA JVAQUA\n• Mantenimiento: 2 g/m³.\n• Choque: 50 g/25 m³.\n• Siempre complementar con el control de pH, cloro, filtración y el protocolo indicado por el Asistente Técnico.''',
            'referencias_tecnicas': '''• EPA registra múltiples familias de alguicidas para piscinas; las instrucciones y compatibilidades son específicas de cada formulación.\n• EPA guidance sobre compuestos de amonio cuaternario: algunas mezclas con detergentes aniónicos reducen eficacia y el contacto concentrado con oxidantes debe evitarse.\n• Las dosis mostradas son referencias internas JVAQUA sujetas a la etiqueta del producto utilizado.''',
            'etiquetas': 'alguicida, algas, agua verde, prevención, mantenimiento, choque, quaternary ammonium, piscina',
        },
    ]

    for item in items:
        defaults = dict(item)
        defaults.update({'tipo': 'biblioteca', 'estado': 'borrador', 'version': '0.9'})
        Contenido.objects.update_or_create(codigo=item['codigo'], defaults=defaults)


def reverse_seed(apps, schema_editor):
    Contenido = apps.get_model('asistente_tecnico', 'ContenidoAcademia')
    Contenido.objects.filter(codigo__in=['BT-Q-001','BT-Q-002','BT-Q-003','BT-Q-004','BT-Q-005'], version='0.9').delete()


class Migration(migrations.Migration):
    dependencies = [('asistente_tecnico', '0003_academia_cms')]
    operations = [migrations.RunPython(seed_biblioteca, reverse_seed)]
