from django.db import migrations


def seed(apps, schema_editor):
    Contenido = apps.get_model('asistente_tecnico', 'ContenidoAcademia')
    items = [
        dict(codigo='AC-FUN-004', titulo='Cómo calcular el volumen de una piscina', slug='calcular-volumen-piscina', tipo='biblioteca', modulo_curso='fundamentos', orden_curso=40, orden=40, nivel='basico', tiempo_lectura_min=7,
             resumen='Aprende a estimar los metros cúbicos de una piscina para dosificar correctamente productos y entender su operación.',
             introduccion='''El volumen es la base de casi todos los cálculos de una piscina. Una dosis correcta depende de saber cuánta agua hay realmente.\n\nLO QUE DEBES RECORDAR\n• Piscina rectangular: largo × ancho × profundidad media.\n• Si hay dos profundidades, usa una profundidad media aproximada.\n• 1 m³ equivale a 1.000 litros.\n• Si la forma es irregular, divide la piscina en zonas simples y suma sus volúmenes.''',
             contenido='''PISCINA RECTANGULAR\nVolumen aproximado = largo × ancho × profundidad media.\n\nPROFUNDIDAD VARIABLE\nSi la piscina pasa de una zona baja a una profunda, una referencia práctica es promediar ambas profundidades cuando la pendiente es relativamente uniforme.\n\nFORMAS IRREGULARES\nDivide mentalmente la piscina en rectángulos, círculos o zonas simples. Calcula cada parte y suma.\n\nPOR QUÉ IMPORTA\nUna diferencia de varios metros cúbicos puede alterar significativamente una dosificación química. Cuando exista duda, utiliza las medidas reales y deja una referencia conservadora en vez de sobredosificar.''',
             buenas_practicas='''• Guarda las medidas de la piscina en su ficha técnica.\n• Verifica medidas cuando el cliente informa un volumen que no coincide con la geometría.\n• Para tratamientos importantes, prefiere un cálculo aproximado razonable antes que una cifra “de memoria”.''',
             errores_comunes='''• Usar solo largo × ancho sin profundidad.\n• Tomar la profundidad máxima como si fuera toda la piscina.\n• Confundir litros con metros cúbicos.\n• Redondear demasiado antes de calcular una dosis.''',
             recomendaciones_jvaqua='''El Asistente Técnico puede calcular el volumen por medidas cuando no conozcas los m³. Utiliza esa opción y confirma que las medidas correspondan a la piscina real.''',
             etiquetas='volumen, metros cubicos, medidas, largo, ancho, profundidad, dosificacion'),
        dict(codigo='AC-FUN-005', titulo='Filtración, circulación y desinfección: las tres trabajan juntas', slug='filtracion-circulacion-desinfeccion', tipo='biblioteca', modulo_curso='fundamentos', orden_curso=50, orden=50, nivel='basico', tiempo_lectura_min=8,
             resumen='Una piscina no se mantiene solo con cloro: necesita circulación adecuada, filtración efectiva y desinfección controlada.',
             introduccion='''Una piscina saludable depende de tres procesos que se complementan.\n\n1. CIRCULACIÓN: mueve el agua.\n2. FILTRACIÓN: retiene partículas.\n3. DESINFECCIÓN: controla microorganismos y oxidación.\n\nSi uno falla, los otros deben trabajar más y el agua puede deteriorarse.''',
             contenido='''CIRCULACIÓN\nLa bomba toma agua desde la piscina, la impulsa a través del sistema y la devuelve por los retornos.\n\nFILTRACIÓN\nEl filtro retiene partículas suspendidas. Un filtro saturado, mal lavado o con medio filtrante deteriorado reduce la calidad del agua.\n\nDESINFECCIÓN\nEl cloro u otro desinfectante mantiene un residual activo para controlar microorganismos. Su eficacia depende también del pH y de la demanda del agua.\n\nUNA PISCINA TRANSPARENTE NO SIEMPRE ESTÁ BIEN\nLa apariencia visual es importante, pero no sustituye una medición de pH y cloro.''',
             buenas_practicas='''• Verifica caudal y retorno de agua.\n• Mantén el filtro en buen estado.\n• Mide pH y cloro antes de ajustar productos.\n• Revisa si el problema es químico, hidráulico o ambos.''',
             errores_comunes='''• Intentar resolver todo agregando más cloro.\n• Ignorar un filtro saturado.\n• Trabajar con la bomba sin cebado.\n• Pensar que agua transparente significa automáticamente agua correctamente desinfectada.''',
             recomendaciones_jvaqua='''Antes de aumentar químicos, confirma que la piscina esté circulando y filtrando correctamente. Un problema hidráulico puede hacer que un buen tratamiento químico parezca ineficaz.''',
             etiquetas='circulacion, filtracion, desinfeccion, bomba, filtro, cloro, fundamentos'),
        dict(codigo='AC-QUI-006', titulo='Cloraminas y olor fuerte a cloro', slug='cloraminas-olor-cloro', tipo='biblioteca', modulo_curso='quimica', orden_curso=60, orden=60, nivel='intermedio', tiempo_lectura_min=8,
             resumen='El olor fuerte no siempre significa “demasiado cloro”. Puede indicar formación de cloraminas por reacción del cloro con contaminantes.',
             introduccion='''Cuando el cloro reacciona con sudor, orina, suciedad y otros compuestos nitrogenados pueden formarse cloraminas. Estas pueden producir olor e irritación.\n\nLO QUE DEBES RECORDAR\n• Olor fuerte no equivale automáticamente a exceso de cloro libre.\n• Hay que medir, no adivinar.\n• La ventilación es especialmente importante en piscinas interiores.''',
             contenido='''QUÉ SON\nLas cloraminas son compuestos formados cuando el cloro se combina con contaminantes nitrogenados.\n\nQUÉ PUEDES NOTAR\n• Olor fuerte característico.\n• Irritación de ojos o vías respiratorias.\n• Menor calidad de desinfección.\n\nQUÉ HACER\nPrimero mide el agua y revisa la condición general. La corrección puede requerir oxidación/choque, filtración y control de carga contaminante según el caso.''',
             buenas_practicas='''• Medir cloro libre y, cuando el sistema lo permita, cloro combinado.\n• Mantener buena ventilación en piscinas cubiertas.\n• Evitar interpretar el olor como una medición química.''',
             errores_comunes='''• Añadir producto sin medir.\n• Confundir olor fuerte con “cloro libre alto” de forma automática.\n• Ignorar la causa de contaminación del agua.''',
             recomendaciones_jvaqua='''Si un cliente reporta olor fuerte o irritación, no respondas únicamente “hay mucho cloro”. Haz una evaluación completa y utiliza el Asistente Técnico para definir el tratamiento según los parámetros disponibles.''',
             referencias_tecnicas='CDC Healthy Swimming — Chloramines and Pool Operation.',
             etiquetas='cloraminas, olor a cloro, irritacion, cloro combinado, contaminacion'),
        dict(codigo='AC-QUI-007', titulo='Lluvia y cambios en el agua de la piscina', slug='lluvia-cambios-agua-piscina', tipo='biblioteca', modulo_curso='quimica', orden_curso=70, orden=70, nivel='basico', tiempo_lectura_min=6,
             resumen='Después de lluvias intensas pueden cambiar el nivel, la carga contaminante y los parámetros; la respuesta correcta comienza midiendo.',
             introduccion='''La lluvia puede introducir polvo, materia orgánica y agua con características distintas a las de la piscina. Además puede elevar el nivel y diluir parcialmente el tratamiento existente.''',
             contenido='''DESPUÉS DE LLUVIA FUERTE\n1. Revisa el nivel de agua.\n2. Retira residuos.\n3. Verifica circulación y filtración.\n4. Mide pH y cloro.\n5. Corrige según lectura y aspecto del agua.\n\nNo existe una dosis universal “para después de lluvia”. La intensidad, volumen añadido y contaminación cambian en cada piscina.''',
             buenas_practicas='''• Revisar canastillas y skimmer después de tormentas.\n• Hacer retrolavado si la presión/estado del filtro lo justifican.\n• Medir antes de dosificar.''',
             errores_comunes='''• Aplicar siempre la misma cantidad de cloro después de cada lluvia.\n• Ignorar el nivel alto de agua.\n• Dejar hojas y residuos dentro de la piscina.''',
             recomendaciones_jvaqua='''Después de lluvia, trata la piscina según su estado real y no según una receta fija.''',
             etiquetas='lluvia, tormenta, nivel agua, ph, cloro, contaminacion'),
        dict(codigo='AC-MAN-013', titulo='Tiempo de filtración: cómo decidirlo', slug='tiempo-filtracion-piscina', tipo='procedimiento', modulo_curso='mantenimiento', orden_curso=130, orden=130, nivel='intermedio', tiempo_lectura_min=8,
             resumen='El tiempo de filtración depende del volumen, caudal, temperatura, uso y condición de la piscina; no existe una cantidad de horas universal.',
             introduccion='''El objetivo de la filtración es hacer circular suficiente agua a través del sistema para mantenerla limpia y ayudar al tratamiento químico. El número de horas depende de la capacidad real del sistema.''',
             contenido='''FACTORES PRINCIPALES\n• Volumen de la piscina.\n• Caudal real de la bomba y pérdidas hidráulicas.\n• Tipo y estado del filtro.\n• Temperatura del agua.\n• Cantidad de bañistas.\n• Exposición a polvo, hojas y lluvia.\n• Estado actual del agua.\n\nUna piscina con mucha carga puede requerir más circulación temporalmente que una piscina estable y de poco uso.''',
             procedimiento='''1. Confirma que bomba y filtro estén trabajando correctamente.\n2. Conoce volumen aproximado y capacidad del sistema.\n3. Revisa el comportamiento real de la piscina.\n4. Ajusta el horario de filtración si el agua pierde claridad, aumenta el uso o sube la temperatura.\n5. Después de tratamientos especiales, sigue el protocolo específico indicado para ese proceso.''',
             buenas_practicas='''• Distribuir la filtración en horarios útiles según operación.\n• Revisar presión y caudal, no solo horas de encendido.\n• Mantener canastillas limpias para no reducir caudal.''',
             errores_comunes='''• Copiar un horario de otra piscina sin comparar volumen/equipo.\n• Aumentar horas para compensar un filtro defectuoso.\n• Creer que bomba encendida significa automáticamente buen caudal.''',
             recomendaciones_jvaqua='''Utiliza el tiempo de filtración como una variable operativa, no como una regla fija. Primero asegúrate de que el sistema realmente esté moviendo agua de forma eficiente.''',
             etiquetas='filtracion, horas, bomba, caudal, recirculacion, mantenimiento'),
        dict(codigo='AC-MAN-014', titulo='Evaporación, reposición y nivel correcto de agua', slug='evaporacion-reposicion-nivel-agua', tipo='procedimiento', modulo_curso='mantenimiento', orden_curso=140, orden=140, nivel='basico', tiempo_lectura_min=6,
             resumen='Aprende a diferenciar una bajada normal de nivel por evaporación de señales que requieren revisar una posible fuga.',
             introduccion='''El nivel de agua cambia por evaporación, uso, salpicaduras, retrolavados y reposiciones. Mantenerlo correctamente ayuda al skimmer y a la bomba.''',
             contenido='''NIVEL DEMASIADO BAJO\nEl skimmer puede aspirar aire y provocar pérdida de cebado.\n\nNIVEL DEMASIADO ALTO\nPuede disminuir la capacidad del skimmer para retirar residuos superficiales.\n\nEVAPORACIÓN\nVaría con temperatura, viento, humedad y exposición. Una pérdida muy superior al comportamiento habitual de la piscina merece investigación.''',
             procedimiento='''1. Observa el nivel respecto al skimmer.\n2. Repón agua cuando esté por debajo del nivel operativo.\n3. Si la pérdida es repetitiva o anormal, registra la observación.\n4. Antes de asegurar que existe una fuga, compara el comportamiento durante varios días y revisa equipos/tuberías visibles.''',
             buenas_practicas='''• Mantener el nivel operativo del skimmer.\n• Revisar pérdidas visibles alrededor de bomba, filtro y válvulas.\n• Registrar reposiciones anormales.''',
             errores_comunes='''• Trabajar con skimmer aspirando aire.\n• Afirmar que hay una fuga únicamente porque bajó el nivel.\n• Ignorar pérdidas constantes en cuarto de bombas.''',
             recomendaciones_jvaqua='''Si el descenso de nivel se vuelve repetitivo, repórtalo a administración y recomienda una revisión específica antes de dar un diagnóstico definitivo.''',
             etiquetas='evaporacion, fuga, nivel agua, skimmer, reposicion'),
        dict(codigo='AC-EQP-009', titulo='Válvulas hidráulicas y control del flujo', slug='valvulas-hidraulicas-piscina', tipo='equipo', modulo_curso='equipos', orden_curso=90, orden=90, nivel='intermedio', tiempo_lectura_min=8,
             resumen='Las válvulas dirigen el flujo entre skimmer, drenaje, aspiración, retornos y equipos. Una posición incorrecta puede reducir caudal o dejar la bomba sin agua.',
             introduccion='''Las válvulas permiten seleccionar por dónde entra y sale el agua del sistema. Comprenderlas evita errores al aspirar, cebar o aislar equipos.''',
             funcionamiento='''Una válvula abre, restringe o cierra una línea hidráulica. En una piscina puede controlar succión desde skimmer/drenaje y retorno hacia diferentes zonas.\n\nCambiar una válvula modifica la resistencia del sistema y, por tanto, el caudal.''',
             componentes='''• Cuerpo de válvula.\n• Manija o actuador.\n• Sellos internos.\n• Uniones/conexiones.\n• Identificación de cada línea.''',
             mantenimiento='''• Mantener identificadas las líneas.\n• Mover válvulas suavemente.\n• Revisar fugas en vástagos/uniones.\n• No forzar una válvula trabada.''',
             fallas_frecuentes='''• Manija dura.\n• Fuga externa.\n• Paso interno aun estando “cerrada”.\n• Posición incorrecta que limita caudal.\n• Aire entrando por una unión en succión.''',
             buenas_practicas='''• Antes de arrancar bomba, confirma que exista un camino abierto de succión y retorno.\n• Fotografía/etiqueta instalaciones complejas.\n• Cambia posiciones con criterio y registra cómo estaba originalmente.''',
             errores_comunes='''• Encender la bomba con líneas cerradas.\n• Girar válvulas sin saber qué línea controlan.\n• Forzar manijas hasta quebrarlas.''',
             recomendaciones_jvaqua='''Cuando llegues a una instalación desconocida, identifica primero cada línea antes de modificar válvulas.''',
             etiquetas='valvulas, hidraulica, skimmer, drenaje, retorno, caudal'),
        dict(codigo='AC-EQP-010', titulo='Temporizador y programación de la bomba', slug='temporizador-programacion-bomba', tipo='equipo', modulo_curso='equipos', orden_curso=100, orden=100, nivel='intermedio', tiempo_lectura_min=7,
             resumen='El temporizador automatiza los periodos de circulación. Aprende qué revisar sin intervenir en trabajos eléctricos que requieren personal calificado.',
             introduccion='''El temporizador permite que la bomba funcione automáticamente en horarios definidos. Puede ser mecánico, digital o formar parte de un sistema de automatización.''',
             funcionamiento='''El dispositivo abre o cierra eléctricamente el circuito de control según una programación. En sistemas más grandes puede accionar contactores en lugar de alimentar directamente el motor.''',
             mantenimiento='''COMPROBACIONES SEGURAS\n• Verificar hora/programación visible.\n• Confirmar si está en AUTO, ON u OFF.\n• Revisar si la bomba responde al horario.\n\nNO REALIZAR\nIntervenciones dentro de tableros energizados, cableado, contactores o protecciones si no eres personal eléctrico calificado.''',
             fallas_frecuentes='''• Reloj desprogramado.\n• Horario incorrecto.\n• Selector en OFF.\n• Pérdida de programación después de corte eléctrico.\n• Falla eléctrica que requiere diagnóstico profesional.''',
             buenas_practicas='''• Registrar el horario configurado.\n• Antes de asumir una falla de bomba, revisar si el control está solicitando encendido.\n• Mantener tableros cerrados y secos.''',
             errores_comunes='''• Manipular cableado energizado.\n• Anular protecciones para “probar”.\n• Cambiar programación sin informar al cliente/administración.''',
             recomendaciones_jvaqua='''El técnico de mantenimiento puede verificar operación y programación básica; cualquier reparación eléctrica debe escalarse a personal calificado.''',
             etiquetas='temporizador, timer, bomba, horario, tablero, automatizacion'),
        dict(codigo='AC-EQP-011', titulo='Clorador salino: funcionamiento básico', slug='clorador-salino-funcionamiento', tipo='equipo', modulo_curso='equipos', orden_curso=110, orden=110, nivel='avanzado', tiempo_lectura_min=9,
             resumen='Un clorador salino genera cloro a partir de sal disuelta mediante electrólisis; no elimina la necesidad de medir y balancear el agua.',
             introduccion='''Los sistemas salinos utilizan una celda electrolítica para convertir cloruros presentes en el agua en especies desinfectantes. La piscina sigue siendo una piscina clorada; el sistema simplemente genera parte del cloro en sitio.''',
             funcionamiento='''El agua con sal atraviesa una celda energizada. La electrólisis genera cloro que luego desinfecta el agua. La producción depende de flujo, salinidad, temperatura, estado de la celda y porcentaje de producción configurado.''',
             componentes='''• Celda electrolítica.\n• Fuente/controlador.\n• Sensor/interruptor de flujo según modelo.\n• Cableado y conexiones.\n• Sal disuelta en el agua.''',
             mantenimiento='''• Revisar indicadores del equipo.\n• Confirmar caudal adecuado.\n• Inspeccionar la celda según fabricante.\n• Controlar acumulación de incrustaciones.\n• Medir química del agua independientemente del porcentaje configurado.''',
             fallas_frecuentes='''• Baja producción por celda incrustada.\n• Flujo insuficiente.\n• Salinidad fuera del rango del fabricante.\n• Celda agotada.\n• Lecturas/alertas del controlador.''',
             buenas_practicas='''• Seguir el manual específico del fabricante.\n• No asumir que “100%” significa un nivel concreto de ppm en la piscina.\n• Medir cloro y pH regularmente.''',
             errores_comunes='''• Pensar que una piscina salina no necesita cloro ni control químico.\n• Limpiar la celda con ácido de forma innecesariamente frecuente.\n• Ignorar flujo y salinidad.''',
             recomendaciones_jvaqua='''Si el clorador marca una alarma, registra el código/modelo y revisa primero flujo, condición de celda y parámetros antes de reemplazar componentes.''',
             etiquetas='clorador salino, sal, celda, electrolisis, cloro, automatizacion'),
        dict(codigo='AC-SEG-003', titulo='Seguridad eléctrica alrededor de piscinas', slug='seguridad-electrica-piscinas', tipo='biblioteca', modulo_curso='seguridad', orden_curso=30, orden=30, nivel='basico', tiempo_lectura_min=7,
             resumen='Agua y electricidad requieren máxima precaución. El técnico debe saber qué puede inspeccionar y cuándo detener el trabajo y escalarlo.',
             introduccion='''La combinación de humedad, motores, luminarias y tableros exige procedimientos seguros. Un técnico de mantenimiento no debe improvisar reparaciones eléctricas.''',
             contenido='''SEÑALES PARA DETENER Y REPORTAR\n• Cableado expuesto.\n• Tablero mojado o sin protección.\n• Olor a quemado.\n• Chispas.\n• Disparos repetitivos de protección.\n• Equipos con carcasa eléctrica dañada.\n\nEl diagnóstico/reparación eléctrica debe realizarlo personal calificado y siguiendo normativa local.''',
             buenas_practicas='''• Mantener manos y área secas al operar controles.\n• No abrir equipos energizados.\n• Reportar protecciones que disparan repetidamente.\n• Mantener tapas y gabinetes correctamente cerrados.''',
             errores_comunes='''• Puentear breakers o protecciones.\n• Manipular conexiones eléctricas mojadas.\n• Reiniciar repetidamente un equipo que dispara protección sin investigar la causa.''',
             recomendaciones_jvaqua='''Ante una condición eléctrica insegura, no intentes “terminar rápido”. Detén la operación del equipo, informa y solicita revisión profesional.''',
             etiquetas='seguridad electrica, tablero, bomba, breaker, riesgo, electricidad'),
        dict(codigo='AC-ADV-001', titulo='Cómo diferenciar un problema químico de uno hidráulico', slug='problema-quimico-vs-hidraulico', tipo='biblioteca', modulo_curso='avanzado', orden_curso=10, orden=10, nivel='avanzado', tiempo_lectura_min=10,
             resumen='Antes de añadir productos, aprende a separar síntomas causados por balance/desinfección de síntomas originados por circulación o filtración deficiente.',
             introduccion='''Muchos problemas de piscina tienen más de una causa. Agua turbia puede aparecer por química incorrecta, filtro deficiente, caudal insuficiente o una combinación.''',
             contenido='''PISTA QUÍMICA\n• pH/cloro fuera de rango.\n• Alta demanda de desinfectante.\n• Algas o contaminación orgánica.\n\nPISTA HIDRÁULICA\n• Retornos débiles.\n• Bomba con aire.\n• Presión anormal.\n• Filtro saturado.\n• Válvulas mal posicionadas.\n\nMÉTODO\n1. Inspección visual.\n2. Medición pH/CL.\n3. Revisión de caudal y bomba.\n4. Revisión de filtro/presión.\n5. Solo entonces decidir el tratamiento.''',
             buenas_practicas='''• Diagnosticar por sistemas.\n• Corregir fallas de circulación antes de esperar resultados perfectos de un tratamiento.\n• Registrar lo observado para seguimiento.''',
             errores_comunes='''• Añadir más químicos cuando la bomba casi no mueve agua.\n• Culpar al filtro sin medir parámetros.\n• Cambiar varias cosas al mismo tiempo y luego no saber qué resolvió el problema.''',
             recomendaciones_jvaqua='''El Asistente Técnico debe recibir parámetros y estado del agua, pero la inspección física de bomba, filtro y caudal sigue siendo fundamental.''',
             etiquetas='diagnostico, quimica, hidraulica, agua turbia, bomba, filtro, avanzado'),
    ]
    for item in items:
        item = dict(item)
        item.update(estado='aprobado', version='1.0', acceso='compartido')
        Contenido.objects.update_or_create(codigo=item['codigo'], defaults=item)


def reverse(apps, schema_editor):
    Contenido = apps.get_model('asistente_tecnico', 'ContenidoAcademia')
    codigos = ['AC-FUN-004','AC-FUN-005','AC-QUI-006','AC-QUI-007','AC-MAN-013','AC-MAN-014','AC-EQP-009','AC-EQP-010','AC-EQP-011','AC-SEG-003','AC-ADV-001']
    Contenido.objects.filter(codigo__in=codigos).delete()


class Migration(migrations.Migration):
    dependencies = [('asistente_tecnico', '0008_academia_procedimientos_campo_v1')]
    operations = [migrations.RunPython(seed, reverse)]
