# Generated by Django 5.2.11 on 2026-03-17 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_actividadsistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='referencia_id',
            field=models.IntegerField(blank=True, help_text='ID del objeto relacionado (ej: mantenimiento)', null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('general', 'General'), ('mantenimiento_hoy', 'Mantenimiento hoy'), ('mantenimiento_manana', 'Mantenimiento mañana')], default='general', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='notificacion',
            unique_together={('user', 'tipo', 'referencia_id')},
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo'], name='dashboard_n_tipo_7d9ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['referencia_id'], name='dashboard_n_referen_3eb0ec_idx'),
        ),
    ]
