# Generated by Django 5.2.11 on 2026-02-11 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('mantenimientos', '0003_usoinsumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usoinsumo',
            name='egreso',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uso_insumo', to='finanzas.egreso'),
        ),
    ]
