# Generated by Django 5.2.11 on 2026-02-11 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0004_usoinsumo_egreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='mantenimientos/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='mantenimientos.mantenimiento')),
            ],
        ),
    ]
