# Generated by Django 5.2.11 on 2026-03-13 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_notificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_sistema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada_en'],
                'indexes': [models.Index(fields=['creada_en'], name='dashboard_a_creada__463bc5_idx'), models.Index(fields=['user', 'creada_en'], name='dashboard_a_user_id_848f53_idx')],
            },
        ),
    ]
