# Generated by Django 5.2.11 on 2026-02-09 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('mantenimientos', '0001_initial'),
        ('trabajadores', '0002_alter_trabajador_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='trabajador',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='trabajadores',
            field=models.ManyToManyField(to='trabajadores.trabajador'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.contrato'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizado', 'Realizado')], default='pendiente', max_length=20),
        ),
    ]
