# Generated by Django 5.2.11 on 2026-02-10 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('mantenimientos', '0002_alter_mantenimiento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_insumos', to='mantenimientos.mantenimiento')),
            ],
        ),
    ]
