# Generated by Django 5.2.11 on 2026-08-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0011_usoinsumo_unidades_liquidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='automatico',
            field=models.BooleanField(default=False, help_text='Indica si fue generado desde la programación automática del contrato.'),
        ),
    ]
