# Generated by Django 5.2.11 on 2026-08-08 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ordentrabajo',
            new_name='ordenes_tra_fecha_e29325_idx',
            old_name='ordenes_tra_fecha_2fd66d_idx',
        ),
        migrations.RenameIndex(
            model_name='ordentrabajo',
            new_name='ordenes_tra_trabaja_2d9f06_idx',
            old_name='ordenes_tra_trabaja_4095c7_idx',
        ),
    ]
