# Generated by Django 5.2.11 on 2026-07-29 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('adelantado', 'Adelantado'), ('50_50', '50/50'), ('por_visita', 'Por visita'), ('fin_mensualidad', 'Fin de la mensualidad'), ('personalizado', 'Personalizado')], default='', max_length=30, verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='forma_pago_personalizada',
            field=models.CharField(blank=True, default='', help_text='Completar únicamente cuando la forma de pago seleccionada sea Personalizado.', max_length=255, verbose_name='Detalle de forma de pago personalizada'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('1_semanal', '1 visita semanal'), ('2_semanales', '2 visitas semanales'), ('3_semanales', '3 visitas semanales'), ('cada_15_dias', 'Cada 15 días'), ('personalizado', 'Personalizado')], default='', max_length=30, verbose_name='Frecuencia del servicio'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='frecuencia_personalizada',
            field=models.CharField(blank=True, default='', help_text='Completar únicamente cuando la frecuencia seleccionada sea Personalizado.', max_length=255, verbose_name='Detalle de frecuencia personalizada'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(blank=True, choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('variable', 'Variable')], default='', max_length=20),
        ),
    ]
