# Generated by Django 5.2.11 on 2026-07-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_contrato_forma_pago_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['-activo', 'cliente__nombre', 'id'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterField(
            model_name='contrato',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('adelantado', 'Adelantado'), ('50_50', '50/50'), ('por_visita', 'Por visita'), ('fin_mensualidad', 'Fin de la mensualidad'), ('personalizado', 'Personalizado')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='forma_pago_personalizada',
            field=models.CharField(blank=True, default='', help_text='Completar únicamente cuando la forma de pago sea personalizada.', max_length=150),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('1_semanal', '1 visita semanal'), ('2_semanales', '2 visitas semanales'), ('3_semanales', '3 visitas semanales'), ('quincenal', 'Cada 15 días'), ('personalizado', 'Personalizado')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='frecuencia_personalizada',
            field=models.CharField(blank=True, default='', help_text='Completar únicamente cuando la frecuencia sea personalizada.', max_length=150),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('variable', 'Variable')], max_length=20),
        ),
    ]
