# Generated by Django 5.2.11 on 2026-08-08 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0007_motor_comercial_financiero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cobro_mes_desfase',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = mes del inicio del periodo; 1 = mes siguiente; 2 = dos meses después.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='dia_pago',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='forma_pago_personalizada',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='frecuencia_personalizada',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='generacion_automatica',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='periodo_dia_inicio',
            field=models.PositiveSmallIntegerField(default=1, help_text='Día en que inicia cada periodo mensual del servicio.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_tecnico_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
