from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[("clientes","0004_ciudad_estructurada"),("contratos","0011_bajas_inteligencia_ciudad"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.AddField(model_name="contrato",name="piscina_largo_m",field=models.DecimalField(blank=True,decimal_places=2,max_digits=7,null=True)),
        migrations.AddField(model_name="contrato",name="piscina_ancho_m",field=models.DecimalField(blank=True,decimal_places=2,max_digits=7,null=True)),
        migrations.AddField(model_name="contrato",name="piscina_profundidad_min_m",field=models.DecimalField(blank=True,decimal_places=2,max_digits=7,null=True)),
        migrations.AddField(model_name="contrato",name="piscina_profundidad_max_m",field=models.DecimalField(blank=True,decimal_places=2,max_digits=7,null=True)),
        migrations.AddField(model_name="contrato",name="piscina_volumen_m3",field=models.DecimalField(blank=True,decimal_places=2,max_digits=9,null=True)),
        migrations.AddField(model_name="contrato",name="piscina_tipo",field=models.CharField(blank=True,default="",max_length=80)),
        migrations.AddField(model_name="contrato",name="piscina_uso",field=models.CharField(blank=True,default="",max_length=80)),
        migrations.AddField(model_name="contrato",name="piscina_filtracion",field=models.CharField(blank=True,default="",max_length=100)),
        migrations.AddField(model_name="contrato",name="piscina_desinfeccion",field=models.CharField(blank=True,default="",max_length=100)),
        migrations.AddField(model_name="contrato",name="piscina_observaciones",field=models.TextField(blank=True,default="")),
        migrations.CreateModel(name="CotizacionMantenimiento",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("creada_en",models.DateTimeField(auto_now_add=True)),("nombre_referencia",models.CharField(blank=True,default="",max_length=150)),("largo_m",models.DecimalField(blank=True,decimal_places=2,max_digits=7,null=True)),("ancho_m",models.DecimalField(blank=True,decimal_places=2,max_digits=7,null=True)),("profundidad_m",models.DecimalField(blank=True,decimal_places=2,max_digits=7,null=True)),("volumen_m3",models.DecimalField(blank=True,decimal_places=2,max_digits=9,null=True)),("frecuencia",models.CharField(choices=[("1_semanal","1 visita semanal"),("2_semanales","2 visitas semanales"),("3_semanales","3 visitas semanales"),("quincenal","Cada 15 días"),("personalizado","Personalizado")],max_length=30)),("quimicos_incluidos",models.BooleanField(default=True)),("equipamiento_mensual",models.DecimalField(decimal_places=2,default=0,max_digits=10)),("ajuste_especial_mensual",models.DecimalField(decimal_places=2,default=0,max_digits=10)),("observaciones",models.TextField(blank=True,default="")),("contratos_similares",models.PositiveIntegerField(default=0)),("promedio_mercado_interno",models.DecimalField(decimal_places=2,default=0,max_digits=10)),("costo_quimico_estimado",models.DecimalField(decimal_places=2,default=0,max_digits=10)),("pago_tecnico_minimo",models.DecimalField(decimal_places=2,default=0,max_digits=10)),("pago_tecnico_recomendado",models.DecimalField(decimal_places=2,default=0,max_digits=10)),("pago_tecnico_maximo",models.DecimalField(decimal_places=2,default=0,max_digits=10)),("precio_minimo",models.DecimalField(decimal_places=2,default=0,max_digits=10)),("precio_recomendado",models.DecimalField(decimal_places=2,default=0,max_digits=10)),("precio_objetivo",models.DecimalField(decimal_places=2,default=0,max_digits=10)),("utilidad_estimada",models.DecimalField(decimal_places=2,default=0,max_digits=10)),("margen_estimado",models.DecimalField(decimal_places=2,default=0,max_digits=6)),("ciudad",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="clientes.ciudad")),("cliente_referencia",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="clientes.cliente")),("creada_por",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to="auth.user"))]),
        migrations.CreateModel(name="EquipamientoContrato",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("nombre",models.CharField(max_length=150)),("costo_jvaqua",models.DecimalField(decimal_places=2,default=0,max_digits=10)),("valor_mensual_adicional",models.DecimalField(decimal_places=2,default=0,max_digits=10)),("fecha_entrega",models.DateField(blank=True,null=True)),("estado",models.CharField(blank=True,default="",max_length=80)),("debe_devolverse",models.BooleanField(default=True)),("activo",models.BooleanField(default=True)),("contrato",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="equipamientos",to="contratos.contrato"))]),
    ]
